### ISSUE TITLE
使用stun主题之后，启动报错

### ISSUE THREAD

**Issue by hans1980775481** [liuyib/hexo-theme-stun#107]
启动报错信息如下：

Unhandled rejection TypeError: D:\hexo-blog\themes\stun\layout\_third-party\search\localsearch.pug:4
    2|   function initSearch() {
    3|     var isXML = true;
  > 4|     var search_path = '!{ config.search.path }';
    5|
    6|     if (!search_path) {
    7|       search_path = 'search.xml';

Cannot read property 'path' of undefined
    at eval (eval at wrap (D:\hexo-blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:2567:60)
    at template (eval at wrap (D:\hexo-blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:5790:72)
    at _View._compiled (D:\hexo-blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\hexo-blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\hexo-blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\hexo-blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\hexo-blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\hexo-blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:490:10)
    at resume_ (_stream_readable.js:975:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Unhandled rejection TypeError: D:\hexo-blog\themes\stun\layout\_third-party\search\localsearch.pug:4
    2|   function initSearch() {
    3|     var isXML = true;
  > 4|     var search_path = '!{ config.search.path }';
    5|
    6|     if (!search_path) {
    7|       search_path = 'search.xml';

Cannot read property 'path' of undefined
    at eval (eval at wrap (D:\hexo-blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:2567:60)
    at template (eval at wrap (D:\hexo-blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:5790:72)
    at _View._compiled (D:\hexo-blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\hexo-blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\hexo-blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\hexo-blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\hexo-blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\hexo-blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:490:10)
    at resume_ (_stream_readable.js:975:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
INFO  Good bye

求解决方式

**Comment by liuyib** [comment]
@hans1980775481 你启用了搜索功能，却没有按照配置来，麻烦你去看文档解决下

**Comment by liuyib** [comment]
同 https://github.com/liuyib/hexo-theme-stun/issues/112
