### ISSUE TITLE
生成的index.html为空

### ISSUE THREAD

**Issue by ShanZJ-gvs** [liuyib/hexo-theme-stun#108]
# 生成的index.html为空

![im8](http://cdn.gvssimux.com/20201016090216.png)

![](http://cdn.gvssimux.com/20201016090606.png)

![](http://cdn.gvssimux.com/20201016090713.png)

```bash
[root@iZm7vqs5ssz3w4Z hexo]# hexo clean
INFO  Validating config
INFO  Deleted database.
INFO  Deleted public folder.
[root@iZm7vqs5ssz3w4Z hexo]# hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 4.77 s
ERROR TypeError: /hexo/themes/stun/layout/_third-party/search/localsearch.pug:4
    2|   function initSearch() {
    3|     var isXML = true;
  > 4|     var search_path = '!{ config.search.path }';
    5| 
    6|     if (!search_path) {
    7|       search_path = 'search.xml';

Cannot read property 'path' of undefined
    at eval (eval at wrap (/hexo/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2671:60)
    at template (eval at wrap (/hexo/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:5894:72)
    at _View._compiled (/hexo/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/hexo/node_modules/hexo/lib/theme/view.js:39:17)
    at /hexo/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/hexo/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:479:10)
    at resume_ (_stream_readable.js:966:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: '/hexo/themes/stun/layout/_third-party/search/localsearch.pug'
}
ERROR TypeError: /hexo/themes/stun/layout/_third-party/search/localsearch.pug:4
    2|   function initSearch() {
    3|     var isXML = true;
  > 4|     var search_path = '!{ config.search.path }';
    5| 
    6|     if (!search_path) {
    7|       search_path = 'search.xml';

Cannot read property 'path' of undefined
    at eval (eval at wrap (/hexo/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2582:60)
    at template (eval at wrap (/hexo/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:5805:72)
    at _View._compiled (/hexo/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/hexo/node_modules/hexo/lib/theme/view.js:39:17)
    at /hexo/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/hexo/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:479:10)
    at resume_ (_stream_readable.js:966:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: '/hexo/themes/stun/layout/_third-party/search/localsearch.pug'
}
ERROR TypeError: /hexo/themes/stun/layout/_third-party/search/localsearch.pug:4
    2|   function initSearch() {
    3|     var isXML = true;
  > 4|     var search_path = '!{ config.search.path }';
    5| 
    6|     if (!search_path) {
    7|       search_path = 'search.xml';

Cannot read property 'path' of undefined
    at eval (eval at wrap (/hexo/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2582:60)
    at template (eval at wrap (/hexo/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:5805:72)
    at _View._compiled (/hexo/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/hexo/node_modules/hexo/lib/theme/view.js:39:17)
    at /hexo/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/hexo/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:479:10)
    at resume_ (_stream_readable.js:966:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: '/hexo/themes/stun/layout/_third-party/search/localsearch.pug'
}
ERROR TypeError: /hexo/themes/stun/layout/_third-party/search/localsearch.pug:4
    2|   function initSearch() {
    3|     var isXML = true;
  > 4|     var search_path = '!{ config.search.path }';
    5| 
    6|     if (!search_path) {
    7|       search_path = 'search.xml';

Cannot read property 'path' of undefined
    at eval (eval at wrap (/hexo/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2582:60)
    at template (eval at wrap (/hexo/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:5805:72)
    at _View._compiled (/hexo/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/hexo/node_modules/hexo/lib/theme/view.js:39:17)
    at /hexo/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/hexo/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:479:10)
    at resume_ (_stream_readable.js:966:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: '/hexo/themes/stun/layout/_third-party/search/localsearch.pug'
}
ERROR TypeError: /hexo/themes/stun/layout/_third-party/search/localsearch.pug:4
    2|   function initSearch() {
    3|     var isXML = true;
  > 4|     var search_path = '!{ config.search.path }';
    5| 
    6|     if (!search_path) {
    7|       search_path = 'search.xml';

Cannot read property 'path' of undefined
    at eval (eval at wrap (/hexo/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2567:60)
    at template (eval at wrap (/hexo/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:5790:72)
    at _View._compiled (/hexo/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/hexo/node_modules/hexo/lib/theme/view.js:39:17)
    at /hexo/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/hexo/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:479:10)
    at resume_ (_stream_readable.js:966:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: '/hexo/themes/stun/layout/_third-party/search/localsearch.pug'
}
INFO  Generated: archives/index.html
INFO  Generated: archives/2020/index.html
INFO  Generated: archives/2020/10/index.html
(node:1452) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1452) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:1452) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:1452) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:1452) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:1452) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Generated: index.html
INFO  Generated: images/cc-by-nc-nd.svg
INFO  Generated: images/icons/favicon-16x16.png
INFO  Generated: images/cc-by-nc-sa.svg
INFO  Generated: images/cc-by-nc.svg
INFO  Generated: images/cc-by-nd.svg
INFO  Generated: images/cc-by-sa.svg
INFO  Generated: images/cc-by.svg
INFO  Generated: images/loading.svg
INFO  Generated: images/icons/favicon-32x32.png
INFO  Generated: images/icons/stun-logo.svg
INFO  Generated: images/algolia.svg
INFO  Generated: js/header.js
INFO  Generated: js/scroll.js
INFO  Generated: js/sidebar.js
INFO  Generated: js/stun-boot.js
INFO  Generated: 2020/10/15/hello-world/index.html
INFO  Generated: js/utils.js
INFO  Generated: css/index.css
INFO  22 files generated in 1.41 s

```

**Comment by liuyib** [comment]
@ShanZJ-gvs 一点都看不懂这个报错吗？这是因为没有配置就启用了搜索功能，和这个 Issue 的问题一样 https://github.com/liuyib/hexo-theme-stun/issues/107。请使用前看文档，看文档，看文档！！！

**Comment by ShanZJ-gvs** [comment]
不好意思....
