### ISSUE TITLE
hexo g 时提示：post-header.pug文件61行出错

### ISSUE THREAD

**Issue by benjamin603** [liuyib/hexo-theme-stun#128]
## 你的反馈

`ERROR TypeError: C:\Users\Benjamin\Documents\githubrepo\benjamin603.github.io\themes\stun\layout\_mixins\post-header.pug:61
    59|             - var iconClass = theme.post_meta.reading_time.icon;
    60|             - var postRead = theme.post_meta.reading_time;
  > 61|             +postMetaItem({
    62|               isIconOnly: isPostMetaIconOnly,
    63|               iconClass: iconClass,
    64|               iconText: __('post.reading_time'),

min2read is not a function
    at Object.pug_interp [as postHeader] (eval at wrap (C:\Users\Benjamin\Documents\githubrepo\benjamin603.github.io\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1068:29)
    at eval (eval at wrap (C:\Users\Benjamin\Documents\githubrepo\benjamin603.github.io\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1146:25)
    at template (eval at wrap (C:\Users\Benjamin\Documents\githubrepo\benjamin603.github.io\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:5990:72)
    at _View._compiled (C:\Users\Benjamin\Documents\githubrepo\benjamin603.github.io\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Benjamin\Documents\githubrepo\benjamin603.github.io\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Benjamin\Documents\githubrepo\benjamin603.github.io\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (C:\Users\Benjamin\Documents\githubrepo\benjamin603.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\Benjamin\Documents\githubrepo\benjamin603.github.io\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\Benjamin\Documents\githubrepo\benjamin603.github.io\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:457:10)
    at resume_ (_stream_readable.js:936:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:17) {
  path: 'C:\\Users\\Benjamin\\Documents\\githubrepo\\benjamin603.github.io\\themes\\stun\\layout\\_mixins\\post-header.pug'
}`

这个文件我没有动过，求助！:cry: 
---

**Comment by benjamin603** [comment]
已解决，hexo-wordcount插件没有安装！
