### ISSUE TITLE
hexo s 后location：4000 报错 full_url_for is not a function问题

### ISSUE THREAD

**Issue by YichangKong** [liuyib/hexo-theme-stun#53]
## I want to create a new issue 

- [] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [] Yes, I have rexad [Hexo Docs page](https://hexo.io/docs/).
- [] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

2020/4/17 The latest version 

Hexo Version
- hexo: 3.9.0
- hexo-cli: 2.0.0
- os: Windows_NT 10.0.18362 win32 x64
- http_parser: 2.8.0
- node: 10.15.3
- v8: 6.8.275.32-node.51
- uv: 1.23.2
- zlib: 1.2.11
- ares: 1.15.0
- modules: 64
- nghttp2: 1.34.0
- napi: 3
- openssl: 1.1.0j
- icu: 62.1
- unicode: 11.0
- cldr: 33.1
- tz: 2018e

Windows

The console error code is as follows
 ``` 
Unhandled rejection TypeError: C:\Users\ThinkPad\blog\themes\stun\layout\_partials\head\head.pug:72
    70|
    71| if theme.canonical
  > 72|   link(ref="canonical" href=full_url_for(page.path))
    73|
    74| if theme.feed.rss
    75|   link(rel="alternate" href=url_for(theme.feed.rss) type="application/atom+xml")

full_url_for is not a function
    at eval (eval at wrap (C:\Users\ThinkPad\blog\node_modules\_pug-runtime@2.0.5@pug-runtime\wrap.js:6:10), <anonymous>:149:77)
    at template (eval at wrap (C:\Users\ThinkPad\blog\node_modules\_pug-runtime@2.0.5@pug-runtime\wrap.js:6:10), <anonymous>:5556:72)
    at Theme._View.View._compiled.locals [as _compiled] (C:\Users\ThinkPad\blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (C:\Users\ThinkPad\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at C:\Users\ThinkPad\blog\node_modules\hexo\lib\hexo\index.js:349:21
    at tryCatcher (C:\Users\ThinkPad\blog\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\ThinkPad\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\ThinkPad\blog\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:929:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
1. Solution
My solution is to directly comment the error statement

**Comment by liuyib** [comment]
@YichangKong  这个是因为 Hexo 版本太低，你把 Hexo 升级到 4.0.0+ 版本就可以了。主题后面会考虑做一些兼容处理。

**Comment by liuyib** [comment]
暂时不考虑兼容 Hexo 4.0.0 以下的版本了。如果遇到这个报错，请升级 Hexo 到 4.0.0+
